### ISSUE TITLE
Spot price for given path

### ISSUE THREAD

**Issue by Nadim-Muhammad** [Staneesh/optionator#18]
Make changes in varcalc.cpp

**Comment by Nadim-Muhammad** [comment]
@Staneesh Can you help me with TODO task you left me to do? I tried to do it, but I am having problems with getting Time to Maturity from the option (which is needed for choosing underlying price at correct date).
Additional question: do we simplify our problem as it is in the email from 23.01 (all times to maturity are set to 60)? I wouldn't change it, because we have most of the code already but it's your call.

**Comment by Staneesh** [comment]
Sure, I'll take a look. Agree to not simplify our code.

**Comment by Staneesh** [comment]
Raised a PR to expose the private `m_timeToMaturity` field via a getter function that you can call like that: 
```{c++}
LongCall option( /* ... */ );
double maturity = option.getTimeToMaturity();
```
